runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  script: index.php

- url: /.*
  script: 2.php

url: /(.*\.(gif|png|jpg|txt))$
  static_files: static/\1
  upload: static/.*\.(gif|png|jpg)$