runtime: php55
api_version: 1
threadsafe: true

handlers:
- url: /
  script: index.php  
  application_readable: true
  Access-Control-Allow-Origin: * 

- url: /.*
  script: 2.php
  application_readable: true
  Access-Control-Allow-Origin: * 
